# Generated by Django 3.2.9 on 2021-12-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Current amount of money')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Final amount of money')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Home name')),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='budget.account')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Label name')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.account', verbose_name='Account')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.home', verbose_name='Home')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('final_datetime', models.DateTimeField(null=True, verbose_name='Time finalized')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Operation amount')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Label description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.account', verbose_name='Account')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.label', verbose_name='Label')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.home', verbose_name='Home'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
