# Generated by Django 3.2.9 on 2021-12-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='budget.account'),
        ),
    ]
