# Generated by Django 3.2.9 on 2021-12-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.home', verbose_name='Home'),
        ),
    ]
