# Generated by Django 3.2.9 on 2021-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time created'),
        ),
    ]
